###generate #1
POST http://localhost:8080/generate
Content-Type: application/json

{
  "original": "https://www.noob-club.ru/index.php?frontpage;p=45"
}

###generate #2
POST http://localhost:8080/generate
Content-Type: application/json

{
  "original": "https://catalog.onliner.by/notebook?page=2"
}

###generate #3
POST http://localhost:8080/generate
Content-Type: application/json

{
  "original": "https://habr.com/ru/news/t/708070/"
}

###redirect
GET http://localhost:8080/?shortLink=/1/noob-club
Accept: application/json

###stat
GET http://localhost:8080/stat/?shortLink=/3/habr
Accept: application/json

###stats
GET http://localhost:8080/stats/?page=1&count=20
Accept: application/json
